# Generated by Django 3.0.8 on 2020-07-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='secret_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_key', models.CharField(max_length=1000)),
                ('receiver_key', models.CharField(max_length=1000)),
            ],
        ),
    ]
