# Generated by Django 3.0.8 on 2020-07-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200704_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret_keys_receiver',
            name='s_index',
        ),
        migrations.AddField(
            model_name='secret_keys',
            name='r_index',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.secret_keys_receiver'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='index',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
